# Generated by Django 2.2.12 on 2020-04-08 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_orders'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Orders',
        ),
    ]
