# Generated by Django 2.2.12 on 2020-04-08 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_delete_orders'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='sub_category',
        ),
    ]
